CREATE TABLE castles (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,

PRIMARY KEY (id)
);

CREATE TABLE knights (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL DEFAULT 'Unknown Knight',
-- name VARCHAR(255) NOT NULL DEFAULT Cool Guy,
castles VARCHAR(255) NOT NULL DEFAULT 'Unknown Castle'
-- castles VARCHAR(255) NOT NULL DEFAULT Unknown Castle
good BOOLEAN NOT NULL DEFAULT 1,
evil BOOLEAN NOT NULL DEFAULT 1,

PRIMARY KEY (id)
);

